import 'bloc/cobrar_twentyfive_bloc.dart';import 'models/cobrar_twentyfive_model.dart';import 'package:flutter/material.dart';import 'package:victor_kobinski_s_application2/core/app_export.dart';import 'package:victor_kobinski_s_application2/widgets/app_bar/appbar_image.dart';import 'package:victor_kobinski_s_application2/widgets/app_bar/appbar_subtitle_3.dart';import 'package:victor_kobinski_s_application2/widgets/app_bar/custom_app_bar.dart';import 'package:victor_kobinski_s_application2/widgets/custom_elevated_button.dart';import 'package:victor_kobinski_s_application2/widgets/custom_icon_button.dart';class CobrarTwentyfiveScreen extends StatelessWidget {const CobrarTwentyfiveScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<CobrarTwentyfiveBloc>(create: (context) => CobrarTwentyfiveBloc(CobrarTwentyfiveState(cobrarTwentyfiveModelObj: CobrarTwentyfiveModel()))..add(CobrarTwentyfiveInitialEvent()), child: CobrarTwentyfiveScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return BlocBuilder<CobrarTwentyfiveBloc, CobrarTwentyfiveState>(builder: (context, state) {return SafeArea(child: Scaffold(backgroundColor: appTheme.gray90002, appBar: CustomAppBar(height: getVerticalSize(79), leadingWidth: 41, leading: AppbarImage(height: getVerticalSize(16), width: getHorizontalSize(9), svgPath: ImageConstant.imgArrowleftOnprimarycontainer, margin: getMargin(left: 32, top: 20, bottom: 19), onTap: () {onTapArrowleft52(context);}), centerTitle: true, title: AppbarSubtitle3(text: "lbl_cobrar".tr), actions: [AppbarImage(height: getVerticalSize(21), width: getHorizontalSize(22), imagePath: ImageConstant.imgFrame45, margin: getMargin(left: 23, top: 17, right: 23, bottom: 17))]), body: Container(width: double.maxFinite, padding: getPadding(left: 17, top: 36, right: 17, bottom: 36), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [Padding(padding: getPadding(left: 4), child: Row(children: [Container(decoration: AppDecoration.txtOutline, child: Text("msg_cobran_a_recebida".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.headlineMediumOnPrimaryContainer)), Container(height: getSize(30), width: getSize(30), margin: getMargin(left: 34, top: 2, bottom: 1), child: Stack(alignment: Alignment.center, children: [CustomImageView(svgPath: ImageConstant.imgGlobe, height: getSize(30), width: getSize(30), alignment: Alignment.center), CustomIconButton(height: 30, width: 30, padding: getPadding(all: 2), decoration: IconButtonStyleHelper.fillGray70001TL15, alignment: Alignment.center, child: CustomImageView(svgPath: ImageConstant.imgArrowup))])), Container(height: getSize(30), width: getSize(30), margin: getMargin(left: 11, top: 2, bottom: 1), child: Stack(alignment: Alignment.center, children: [CustomImageView(svgPath: ImageConstant.imgGroup44, height: getSize(30), width: getSize(30), alignment: Alignment.center), CustomIconButton(height: 30, width: 30, padding: getPadding(all: 2), decoration: IconButtonStyleHelper.fillOnPrimaryContainer, alignment: Alignment.center, child: CustomImageView(svgPath: ImageConstant.imgArrowdown))]))])), Align(alignment: Alignment.center, child: Padding(padding: getPadding(top: 159), child: Text("msg_sem_movimenta_es".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.headlineMediumGray60002))), Spacer(), CustomElevatedButton(text: "lbl_nova_cobran_a".tr, margin: getMargin(right: 13), buttonStyle: CustomButtonStyles.fillPrimaryTL6.copyWith(fixedSize: MaterialStateProperty.all<Size>(Size(double.maxFinite, getVerticalSize(52)))), buttonTextStyle: theme.textTheme.bodyLarge!)]))));}); } 


/// Navigates to the previous screen.
///
/// This function takes a [BuildContext] object as a parameter, which is
/// used to build the navigation stack. When the action is triggered, this
/// function uses the [NavigatorService] to navigate to the previous screen
/// in the navigation stack.
onTapArrowleft52(BuildContext context) { NavigatorService.goBack(); } 
 }
