import '../emitir_four_screen/widgets/emitir_four_item_widget.dart';import 'bloc/emitir_four_bloc.dart';import 'models/emitir_four_item_model.dart';import 'models/emitir_four_model.dart';import 'package:flutter/material.dart';import 'package:victor_kobinski_s_application2/core/app_export.dart';import 'package:victor_kobinski_s_application2/widgets/app_bar/appbar_image.dart';import 'package:victor_kobinski_s_application2/widgets/app_bar/appbar_subtitle_3.dart';import 'package:victor_kobinski_s_application2/widgets/app_bar/custom_app_bar.dart';import 'package:victor_kobinski_s_application2/widgets/custom_outlined_button.dart';class EmitirFourScreen extends StatelessWidget {const EmitirFourScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<EmitirFourBloc>(create: (context) => EmitirFourBloc(EmitirFourState(emitirFourModelObj: EmitirFourModel()))..add(EmitirFourInitialEvent()), child: EmitirFourScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.onErrorContainer, appBar: CustomAppBar(height: getVerticalSize(79), leadingWidth: 41, leading: AppbarImage(height: getVerticalSize(16), width: getHorizontalSize(9), svgPath: ImageConstant.imgArrowleftOnprimarycontainer, margin: getMargin(left: 32, top: 19, bottom: 20), onTap: () {onTapArrowleft54(context);}), centerTitle: true, title: AppbarSubtitle3(text: "lbl_nova_cobran_a".tr), actions: [AppbarImage(height: getVerticalSize(21), width: getHorizontalSize(22), imagePath: ImageConstant.imgFrame45, margin: getMargin(left: 23, top: 16, right: 23, bottom: 18))]), body: Container(width: double.maxFinite, padding: getPadding(left: 19, top: 15, right: 19, bottom: 15), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [Container(width: getHorizontalSize(209), margin: getMargin(left: 1), child: Text("msg_insira_quem_ser".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.headlineMediumOnPrimaryContainer)), Padding(padding: getPadding(top: 37), child: Text("lbl_nome_cpf_cnpj".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.headlineSmallGray60002.copyWith(letterSpacing: getHorizontalSize(0.96)))), Padding(padding: getPadding(top: 3), child: Divider(height: getVerticalSize(1), thickness: getVerticalSize(1), color: appTheme.gray50002, endIndent: getHorizontalSize(9))), Padding(padding: getPadding(top: 75), child: Row(children: [CustomOutlinedButton(text: "lbl_contatos".tr, buttonStyle: CustomButtonStyles.outlineOnPrimaryContainer.copyWith(fixedSize: MaterialStateProperty.all<Size>(Size(getHorizontalSize(167), getVerticalSize(39)))), buttonTextStyle: CustomTextStyles.bodyLargeOnPrimaryContainer), CustomOutlinedButton(text: "lbl_recentes".tr, margin: getMargin(left: 9), buttonStyle: CustomButtonStyles.outlineGray70001.copyWith(fixedSize: MaterialStateProperty.all<Size>(Size(getHorizontalSize(167), getVerticalSize(39)))), buttonTextStyle: CustomTextStyles.bodyLargeGray50002_1)])), Expanded(child: Padding(padding: getPadding(top: 22, right: 9), child: BlocSelector<EmitirFourBloc, EmitirFourState, EmitirFourModel?>(selector: (state) => state.emitirFourModelObj, builder: (context, emitirFourModelObj) {return ListView.separated(physics: BouncingScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: getVerticalSize(12));}, itemCount: emitirFourModelObj?.emitirFourItemList.length ?? 0, itemBuilder: (context, index) {EmitirFourItemModel model = emitirFourModelObj?.emitirFourItemList[index] ?? EmitirFourItemModel(); return EmitirFourItemWidget(model);});})))])))); } 


/// Navigates to the previous screen.
///
/// This function takes a [BuildContext] object as a parameter, which is
/// used to build the navigation stack. When the action is triggered, this
/// function uses the [NavigatorService] to navigate to the previous screen
/// in the navigation stack.
onTapArrowleft54(BuildContext context) { NavigatorService.goBack(); } 
 }
