import 'bloc/emitir_three_tab_container_bloc.dart';import 'models/emitir_three_tab_container_model.dart';import 'package:flutter/material.dart';import 'package:victor_kobinski_s_application2/core/app_export.dart';import 'package:victor_kobinski_s_application2/presentation/emitir_three_page/emitir_three_page.dart';import 'package:victor_kobinski_s_application2/widgets/app_bar/appbar_image.dart';import 'package:victor_kobinski_s_application2/widgets/app_bar/appbar_subtitle_3.dart';import 'package:victor_kobinski_s_application2/widgets/app_bar/custom_app_bar.dart';class EmitirThreeTabContainerScreen extends StatefulWidget {const EmitirThreeTabContainerScreen({Key? key}) : super(key: key);

@override EmitirThreeTabContainerScreenState createState() =>  EmitirThreeTabContainerScreenState();
static Widget builder(BuildContext context) { return BlocProvider<EmitirThreeTabContainerBloc>(create: (context) => EmitirThreeTabContainerBloc(EmitirThreeTabContainerState(emitirThreeTabContainerModelObj: EmitirThreeTabContainerModel()))..add(EmitirThreeTabContainerInitialEvent()), child: EmitirThreeTabContainerScreen()); } 
 }

// ignore_for_file: must_be_immutable
class EmitirThreeTabContainerScreenState extends State<EmitirThreeTabContainerScreen> with  TickerProviderStateMixin {late TabController tabviewController;

@override void initState() { super.initState(); tabviewController = TabController(length: 2, vsync: this); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return BlocBuilder<EmitirThreeTabContainerBloc, EmitirThreeTabContainerState>(builder: (context, state) {return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.onErrorContainer, appBar: CustomAppBar(height: getVerticalSize(79), leadingWidth: 41, leading: AppbarImage(height: getVerticalSize(16), width: getHorizontalSize(9), svgPath: ImageConstant.imgArrowleftOnprimarycontainer, margin: getMargin(left: 32, top: 19, bottom: 20), onTap: () {onTapArrowleft35(context);}), centerTitle: true, title: AppbarSubtitle3(text: "lbl_repassar".tr), actions: [AppbarImage(height: getVerticalSize(21), width: getHorizontalSize(22), imagePath: ImageConstant.imgFrame45, margin: getMargin(left: 23, top: 16, right: 23, bottom: 18))]), body: SizedBox(width: double.maxFinite, child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [Padding(padding: getPadding(left: 20, top: 36), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(width: getHorizontalSize(230), child: Text("msg_insira_os_dados2".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.headlineMediumOnPrimaryContainer)), CustomImageView(svgPath: ImageConstant.imgQrcode, height: getSize(20), width: getSize(20), margin: getMargin(left: 94, top: 7, bottom: 44))])), Align(alignment: Alignment.centerLeft, child: Padding(padding: getPadding(left: 19, top: 32), child: Text("lbl_nome_cpf_cnpj".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.headlineSmallGray60002.copyWith(letterSpacing: getHorizontalSize(0.96))))), Padding(padding: getPadding(top: 3), child: Divider(height: getVerticalSize(1), thickness: getVerticalSize(1), color: appTheme.gray50002, indent: getHorizontalSize(19), endIndent: getHorizontalSize(28))), Container(height: getVerticalSize(39), width: getHorizontalSize(343), margin: getMargin(top: 55), child: TabBar(controller: tabviewController, labelColor: appTheme.gray50002, labelStyle: TextStyle(), unselectedLabelColor: theme.colorScheme.onPrimaryContainer, unselectedLabelStyle: TextStyle(), indicator: BoxDecoration(borderRadius: BorderRadius.circular(getHorizontalSize(2)), border: Border.all(color: appTheme.gray70001, width: getHorizontalSize(1), strokeAlign: strokeAlignCenter)), tabs: [Tab(child: Text("lbl_contatos".tr, overflow: TextOverflow.ellipsis)), Tab(child: Text("lbl_recentes".tr, overflow: TextOverflow.ellipsis))])), Expanded(child: SizedBox(height: getVerticalSize(435), child: TabBarView(controller: tabviewController, children: [EmitirThreePage.builder(context), EmitirThreePage.builder(context)])))]))));}); } 


/// Navigates to the previous screen.
///
/// This function takes a [BuildContext] object as a parameter, which is
/// used to build the navigation stack. When the action is triggered, this
/// function uses the [NavigatorService] to navigate to the previous screen
/// in the navigation stack.
onTapArrowleft35(BuildContext context) { NavigatorService.goBack(); } 
 }
