import '../emitir_two_screen/widgets/emitir_two_item_widget.dart';import 'bloc/emitir_two_bloc.dart';import 'models/emitir_two_item_model.dart';import 'models/emitir_two_model.dart';import 'package:flutter/material.dart';import 'package:victor_kobinski_s_application2/core/app_export.dart';import 'package:victor_kobinski_s_application2/widgets/app_bar/appbar_image.dart';import 'package:victor_kobinski_s_application2/widgets/app_bar/appbar_subtitle_3.dart';import 'package:victor_kobinski_s_application2/widgets/app_bar/custom_app_bar.dart';import 'package:victor_kobinski_s_application2/widgets/custom_outlined_button.dart';class EmitirTwoScreen extends StatelessWidget {const EmitirTwoScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<EmitirTwoBloc>(create: (context) => EmitirTwoBloc(EmitirTwoState(emitirTwoModelObj: EmitirTwoModel()))..add(EmitirTwoInitialEvent()), child: EmitirTwoScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.onErrorContainer, appBar: CustomAppBar(height: getVerticalSize(78), leadingWidth: 41, leading: AppbarImage(height: getVerticalSize(16), width: getHorizontalSize(9), svgPath: ImageConstant.imgArrowleftOnprimarycontainer, margin: getMargin(left: 32, top: 20, bottom: 19), onTap: () {onTapArrowleft7(context);}), centerTitle: true, title: AppbarSubtitle3(text: "lbl_prazo".tr), actions: [AppbarImage(height: getVerticalSize(21), width: getHorizontalSize(22), imagePath: ImageConstant.imgFrame45, margin: getMargin(left: 23, top: 17, right: 23, bottom: 17))]), body: Container(width: double.maxFinite, padding: getPadding(top: 37, bottom: 37), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [Container(width: getHorizontalSize(230), margin: getMargin(left: 15), child: Text("msg_insira_os_dados".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.headlineMediumOnPrimaryContainer)), Padding(padding: getPadding(left: 15, top: 35), child: Text("msg_nome_cpf_cnpj_ou".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.titleLargeGray60002.copyWith(letterSpacing: getHorizontalSize(0.8)))), Divider(height: getVerticalSize(1), thickness: getVerticalSize(1), color: appTheme.gray50002), Align(alignment: Alignment.center, child: Padding(padding: getPadding(left: 24, top: 60), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomOutlinedButton(text: "lbl_contatos".tr, buttonStyle: CustomButtonStyles.outlineOnPrimaryContainer.copyWith(fixedSize: MaterialStateProperty.all<Size>(Size(getHorizontalSize(167), getVerticalSize(39)))), buttonTextStyle: CustomTextStyles.bodyLargeOnPrimaryContainer), CustomOutlinedButton(text: "lbl_recentes".tr, margin: getMargin(left: 9), buttonStyle: CustomButtonStyles.outlineGray70001.copyWith(fixedSize: MaterialStateProperty.all<Size>(Size(getHorizontalSize(167), getVerticalSize(39)))), buttonTextStyle: CustomTextStyles.bodyLargeGray50002_1)]))), Expanded(child: Align(alignment: Alignment.center, child: Padding(padding: getPadding(left: 24, top: 22, right: 23), child: BlocSelector<EmitirTwoBloc, EmitirTwoState, EmitirTwoModel?>(selector: (state) => state.emitirTwoModelObj, builder: (context, emitirTwoModelObj) {return ListView.separated(physics: BouncingScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: getVerticalSize(12));}, itemCount: emitirTwoModelObj?.emitirTwoItemList.length ?? 0, itemBuilder: (context, index) {EmitirTwoItemModel model = emitirTwoModelObj?.emitirTwoItemList[index] ?? EmitirTwoItemModel(); return EmitirTwoItemWidget(model);});}))))])))); } 


/// Navigates to the previous screen.
///
/// This function takes a [BuildContext] object as a parameter, which is
/// used to build the navigation stack. When the action is triggered, this
/// function uses the [NavigatorService] to navigate to the previous screen
/// in the navigation stack.
onTapArrowleft7(BuildContext context) { NavigatorService.goBack(); } 
 }
