import 'bloc/bolex_seventyseven_bloc.dart';import 'models/bolex_seventyseven_model.dart';import 'package:flutter/material.dart';import 'package:victor_kobinski_s_application2/core/app_export.dart';import 'package:victor_kobinski_s_application2/widgets/app_bar/appbar_image.dart';import 'package:victor_kobinski_s_application2/widgets/app_bar/appbar_subtitle_3.dart';import 'package:victor_kobinski_s_application2/widgets/app_bar/custom_app_bar.dart';import 'package:victor_kobinski_s_application2/widgets/custom_elevated_button.dart';class BolexSeventysevenScreen extends StatelessWidget {const BolexSeventysevenScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<BolexSeventysevenBloc>(create: (context) => BolexSeventysevenBloc(BolexSeventysevenState(bolexSeventysevenModelObj: BolexSeventysevenModel()))..add(BolexSeventysevenInitialEvent()), child: BolexSeventysevenScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return BlocBuilder<BolexSeventysevenBloc, BolexSeventysevenState>(builder: (context, state) {return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.onErrorContainer, appBar: CustomAppBar(height: getVerticalSize(78), leadingWidth: 41, leading: AppbarImage(height: getVerticalSize(16), width: getHorizontalSize(9), svgPath: ImageConstant.imgArrowleftOnprimarycontainer, margin: getMargin(left: 32, top: 19, bottom: 20), onTap: () {onTapArrowleft55(context);}), centerTitle: true, title: AppbarSubtitle3(text: "lbl_nova_cobran_a".tr), actions: [AppbarImage(height: getVerticalSize(21), width: getHorizontalSize(22), imagePath: ImageConstant.imgLogobolexbrancavertical21x22, margin: getMargin(left: 23, top: 16, right: 23, bottom: 18))]), body: Container(width: double.maxFinite, padding: getPadding(left: 18, top: 29, right: 18, bottom: 29), child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [Align(alignment: Alignment.centerLeft, child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: getPadding(bottom: 68), child: Text("lbl_r".tr.toUpperCase(), overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.headlineLargeDeeporangeA200)), Padding(padding: getPadding(left: 18, top: 32), child: Text("lbl_700_00".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.displayLargeDeeporangeA200.copyWith(letterSpacing: getHorizontalSize(2.4))))])), Padding(padding: getPadding(top: 4), child: Text("lbl_florzinha_jota".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.headlineSmallDeeporangeA200.copyWith(letterSpacing: getHorizontalSize(0.96)))), Padding(padding: getPadding(top: 101), child: Text("msg_quantidade_de_parcelas".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.titleMediumGray40001)), CustomElevatedButton(text: "lbl_pagamento_em_1x".tr.toUpperCase(), margin: getMargin(top: 7), rightIcon: Container(margin: getMargin(left: 12), child: CustomImageView(svgPath: ImageConstant.imgPolygon1Onprimarycontainer)), buttonStyle: CustomButtonStyles.fillGray90001TL16.copyWith(fixedSize: MaterialStateProperty.all<Size>(Size(getHorizontalSize(244), getVerticalSize(89)))), buttonTextStyle: CustomTextStyles.titleMediumOnPrimaryContainerBold), CustomElevatedButton(text: "msg_descri_o_da_cobran_a".tr, margin: getMargin(top: 26), buttonStyle: CustomButtonStyles.fillGray90001TL16.copyWith(fixedSize: MaterialStateProperty.all<Size>(Size(getHorizontalSize(244), getVerticalSize(89)))), buttonTextStyle: CustomTextStyles.bodyLargeGray40001), Spacer(), CustomImageView(svgPath: ImageConstant.imgArrowrightOnprimarycontainer, height: getSize(44), width: getSize(44), margin: getMargin(bottom: 44))]))));}); } 


/// Navigates to the previous screen.
///
/// This function takes a [BuildContext] object as a parameter, which is
/// used to build the navigation stack. When the action is triggered, this
/// function uses the [NavigatorService] to navigate to the previous screen
/// in the navigation stack.
onTapArrowleft55(BuildContext context) { NavigatorService.goBack(); } 
 }
