import 'bloc/emitir_six_bloc.dart';import 'models/emitir_six_model.dart';import 'package:flutter/material.dart';import 'package:victor_kobinski_s_application2/core/app_export.dart';import 'package:victor_kobinski_s_application2/widgets/app_bar/appbar_image.dart';import 'package:victor_kobinski_s_application2/widgets/app_bar/appbar_subtitle_3.dart';import 'package:victor_kobinski_s_application2/widgets/app_bar/custom_app_bar.dart';import 'package:victor_kobinski_s_application2/widgets/custom_elevated_button.dart';class EmitirSixScreen extends StatelessWidget {const EmitirSixScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<EmitirSixBloc>(create: (context) => EmitirSixBloc(EmitirSixState(emitirSixModelObj: EmitirSixModel()))..add(EmitirSixInitialEvent()), child: EmitirSixScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return BlocBuilder<EmitirSixBloc, EmitirSixState>(builder: (context, state) {return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.onErrorContainer, appBar: CustomAppBar(height: getVerticalSize(79), leadingWidth: 41, leading: AppbarImage(height: getVerticalSize(16), width: getHorizontalSize(9), svgPath: ImageConstant.imgArrowleftOnprimarycontainer, margin: getMargin(left: 32, top: 19, bottom: 20), onTap: () {onTapArrowleft61(context);}), centerTitle: true, title: AppbarSubtitle3(text: "lbl_transferir".tr), actions: [AppbarImage(height: getSize(20), width: getSize(20), svgPath: ImageConstant.imgQrcode, margin: getMargin(left: 22, top: 17, right: 16, bottom: 2)), AppbarImage(height: getSize(23), width: getSize(23), imagePath: ImageConstant.imgCopiade1, margin: getMargin(left: 15, top: 16, right: 16)), AppbarImage(height: getVerticalSize(21), width: getHorizontalSize(22), imagePath: ImageConstant.imgFrame45, margin: getMargin(left: 15, top: 16, right: 38, bottom: 2))]), body: Container(width: double.maxFinite, padding: getPadding(top: 37, bottom: 37), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [Container(width: getHorizontalSize(309), margin: getMargin(left: 16, right: 65), child: Text("msg_digite_o_valor_que".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.headlineMediumOnPrimaryContainer)), Padding(padding: getPadding(left: 16, top: 31), child: Text("lbl_r_700_00".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.headlineMediumBluegray10001.copyWith(letterSpacing: getHorizontalSize(1.12)))), Divider(height: getVerticalSize(1), thickness: getVerticalSize(1), color: appTheme.gray50002), Padding(padding: getPadding(left: 16, top: 11), child: Text("msg_valor_dispon_vel2".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.bodyLargeGray50002_1)), Padding(padding: getPadding(left: 16), child: Text("lbl_r_2_700_00".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.bodyLargeGray5000218.copyWith(letterSpacing: getHorizontalSize(0.72)))), Spacer(), CustomElevatedButton(text: "lbl_confirmar".tr, margin: getMargin(left: 23, right: 24), buttonStyle: CustomButtonStyles.fillPrimaryTL6.copyWith(fixedSize: MaterialStateProperty.all<Size>(Size(double.maxFinite, getVerticalSize(52)))), buttonTextStyle: theme.textTheme.bodyLarge!, alignment: Alignment.center)]))));}); } 


/// Navigates to the previous screen.
///
/// This function takes a [BuildContext] object as a parameter, which is
/// used to build the navigation stack. When the action is triggered, this
/// function uses the [NavigatorService] to navigate to the previous screen
/// in the navigation stack.
onTapArrowleft61(BuildContext context) { NavigatorService.goBack(); } 
 }
